# Generated by Django 4.1.3 on 2022-11-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_order_adis_customer_order_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Adis',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='new',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='newBrand',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='newsds',
        ),
    ]
