# Generated by Django 4.1.3 on 2022-11-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_agent_order_adis_agent_order_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='Adis',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='new',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='newBrand',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='newsds',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store_agent',
            name='Adis',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store_agent',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store_agent',
            name='newBrand',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store_agent',
            name='newsds',
        ),
    ]
