# Generated by Django 4.1.3 on 2022-11-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_company_store_onmap_alter_region_coverarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Adis',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='newBrand',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='newsds',
        ),
    ]
