# Generated by Django 3.2.9 on 2022-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_remove_product_amount_in_store_adis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yenePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=2000, null=True)),
                ('MerchantId', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
