# Generated by Django 3.2.9 on 2022-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_yenepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(blank=True, default='Product_img/castle-beer.jpg', null=True, upload_to='Product_img/')),
                ('Price_in_botle_Agent_buy', models.FloatField(blank=True, null=True)),
                ('Price_in_creates_Agent_buy', models.FloatField(blank=True, null=True)),
                ('Price_in_botle_Agent_sell', models.FloatField(blank=True, null=True)),
                ('Price_in_creates_Agent_sell', models.FloatField(blank=True, null=True)),
                ('Price_in_botle_Custom_recom', models.FloatField(blank=True, null=True)),
                ('Price_in_creates_Custom_recom', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
