# Generated by Django 3.2.9 on 2022-11-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_productnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnew',
            name='Price_in_creates_Custom_recom',
        ),
    ]
